fspath: /home/oberljn/iot_bot_det/fs
# Storage path

network_context: Home IoT
# Used as model set name

pcaps:
# File name, w/o extension, becomes set variable name
# Null is benign, or otherwise a control set 
- name: 2019-01-10-19-22-51-192.168.1.198
  target_ips:
  - 192.168.1.198
- name: 2018-09-21-capture
  target_ips: Null
- name: 2018-12-21-15-50-14-192.168.1.195
  target_ips:
  - 192.168.1.195
    
sample:
  every_second: 10
  batch_duration: 5 # Less than every_second, considering startup

fields:
# Keys are verbatum packet capture tool
  frame.time:
    capture: True
    aka: Ftime
  frame.len:
    capture: False
    aka: Flen
  #frame.protocols
  #_ws.col.Protocol
  #eth.src
  #eth.dst
  ip.proto:
    capture: False
    aka: P
  ip.src:
   capture: True
   aka:  Sip
  ip.dst:
   capture: True
   aka:  Dip
  #tcp.seq
  tcp.srcport:
    capture: True
    aka: Sporttcp
  tcp.dstport:
    capture: True
    aka: Dporttcp
  udp.srcport:
    capture: True
    aka: Sportudp
  udp.dstport:
    capture: True
    aka: Dportudp
  tcp.flags:
    capture: True
    aka: FG
  tcp.payload:
    capture: False
    aka: P

ports:
# Port list
# Feature selection makes use of this ports list.
# Any other port found will be labeled 'other'.
# Thus this list may be a whitelist and blacklist.
# Current list is based on 'nmap --top-ports 20 localhost'
#- 21    # ftp
- 22    # ssh
#- 23    # telnet
#- 25    # smtp
- 53    # domain
- 80    # http
#- 110   # pop3
#- 111   # rpcbind
#- 135   # msrpc
#- 139   # netbios-ssn
#- 143   # imap
- 443   # https
#- 445   # microsoft-ds
#- 993   # imaps
#- 995   # pop3s
#- 1723  # pptp
#- 3306  # mysql
#- 3389  # ms-wbt-server
#- 5900  # vnc
#- 8080  # http-proxy
