fspath: /home/oberljn/iot_bot_det/fs
# Storage path

network_context: GCP Server
# Used as model set name

pcaps:
# File name, w/o extension, becomes set variable name
# Null is benign, or otherwise a control set 
- name: ~
  target_ips:
  - ~
    
sample:
  every_second: 60
  batch_duration: 10 # Less than every_second, considering startup

mtu: 1600


fields:
# Keys are verbatum packet capture tool
# Adding or removing fields does not change pcap2vec functions,
# but it ought to
  frame.time:
    capture: True
    aka: Ftime
  frame.len:
    capture: False
    aka: Flen
  #frame.protocols
  #_ws.col.Protocol
  #eth.src
  #eth.dst
  ip.proto:
    capture: False
    aka: P
  ip.src:
   capture: True
   aka:  Sip
  ip.dst:
   capture: True
   aka:  Dip
  #tcp.seq
  tcp.srcport:
    capture: True
    aka: Sporttcp
  tcp.dstport:
    capture: True
    aka: Dporttcp
  udp.srcport:
    capture: True
    aka: Sportudp
  udp.dstport:
    capture: True
    aka: Dportudp
  tcp.flags:
    capture: True
    aka: FG
  tcp.payload:
    capture: False
    aka: P

ports:
# Port list
# Feature selection makes use of this ports list.
# Any other port found will be labeled 'other'.
# Thus this list may be a whitelist and blacklist.
# Try 'nmap --top-ports 20 localhost'
# This list based on 1000 packet sample,
# taking top 25% most frequent
- 22
- 33448
- 50740
- 55310
- 80
- 443
